version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq_pokemon_lab
    ports:
      - "5672:5672"  
      - "15672:15672" 
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq 
    healthcheck: 
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 10 


  lcp:
    build:
      context: . 
      dockerfile: LCP/Dockerfile 
    container_name: lcp_service
    ports:
      - "50051:50051" 
    depends_on:
      rabbitmq:
        condition: service_healthy

  snp:
    build:
      context: .
      dockerfile: SNP/Dockerfile
    container_name: snp_service
    depends_on:
      rabbitmq:
        condition: service_healthy

  cdp:
    build:
      context: .
      dockerfile: CDP/Dockerfile
    container_name: cdp_service
    depends_on:
      rabbitmq:
        condition: service_healthy
      



  gimnasios: 
    build:
      context: .
      dockerfile: Gym/Dockerfile
    container_name: gimnasios_regionales_service
    
    ports:
      - "50052:50052" # Kanto
      - "50053:50053" # Johto
      - "50054:50054" # Hoenn
      - "50055:50055" # Sinnoh
      - "50056:50056" # Teselia
      - "50057:50057" # Kalos
      - "50058:50058" # Alola
      - "50059:50059" # Galar
      - "50060:50060" # Paldea
    depends_on:
      rabbitmq:
        condition: service_healthy


  entrenador: 
    build:
      context: .
      dockerfile: Entrenador/Dockerfile
    container_name: entrenador_client
    stdin_open: true 
    tty: true        
    depends_on:
      rabbitmq:
        condition: service_healthy


volumes:
  rabbitmq_data: 