// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/logic.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum para especificar la razón del rechazo de inscripción
type RazonRechazoInscripcion int32

const (
	RazonRechazoInscripcion_RAZON_DESCONOCIDA               RazonRechazoInscripcion = 0 // Razón no especificada o desconocida
	RazonRechazoInscripcion_RECHAZO_POR_SUSPENSION          RazonRechazoInscripcion = 1 // Entrenador está suspendido
	RazonRechazoInscripcion_RECHAZO_YA_INSCRITO_OTRO_TORNEO RazonRechazoInscripcion = 2 // Entrenador ya inscrito en un torneo diferente
	RazonRechazoInscripcion_RECHAZO_TORNEO_NO_EXISTE        RazonRechazoInscripcion = 3 // El torneo solicitado no existe
)

// Enum value maps for RazonRechazoInscripcion.
var (
	RazonRechazoInscripcion_name = map[int32]string{
		0: "RAZON_DESCONOCIDA",
		1: "RECHAZO_POR_SUSPENSION",
		2: "RECHAZO_YA_INSCRITO_OTRO_TORNEO",
		3: "RECHAZO_TORNEO_NO_EXISTE",
	}
	RazonRechazoInscripcion_value = map[string]int32{
		"RAZON_DESCONOCIDA":               0,
		"RECHAZO_POR_SUSPENSION":          1,
		"RECHAZO_YA_INSCRITO_OTRO_TORNEO": 2,
		"RECHAZO_TORNEO_NO_EXISTE":        3,
	}
)

func (x RazonRechazoInscripcion) Enum() *RazonRechazoInscripcion {
	p := new(RazonRechazoInscripcion)
	*p = x
	return p
}

func (x RazonRechazoInscripcion) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RazonRechazoInscripcion) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_logic_proto_enumTypes[0].Descriptor()
}

func (RazonRechazoInscripcion) Type() protoreflect.EnumType {
	return &file_proto_logic_proto_enumTypes[0]
}

func (x RazonRechazoInscripcion) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RazonRechazoInscripcion.Descriptor instead.
func (RazonRechazoInscripcion) EnumDescriptor() ([]byte, []int) {
	return file_proto_logic_proto_rawDescGZIP(), []int{0}
}

// --- Mensajes para ConsultarTorneosDisponibles ---
type Torneo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`         // ID único del torneo
	Region        string                 `protobuf:"bytes,2,opt,name=region,proto3" json:"region,omitempty"` // Región del torneo
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Torneo) Reset() {
	*x = Torneo{}
	mi := &file_proto_logic_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Torneo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Torneo) ProtoMessage() {}

func (x *Torneo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Torneo.ProtoReflect.Descriptor instead.
func (*Torneo) Descriptor() ([]byte, []int) {
	return file_proto_logic_proto_rawDescGZIP(), []int{0}
}

func (x *Torneo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Torneo) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

type TorneosRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SolicitanteInfo string                 `protobuf:"bytes,1,opt,name=solicitante_info,json=solicitanteInfo,proto3" json:"solicitante_info,omitempty"` // ej: "Entrenador cliente solicitando torneos"
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TorneosRequest) Reset() {
	*x = TorneosRequest{}
	mi := &file_proto_logic_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TorneosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TorneosRequest) ProtoMessage() {}

func (x *TorneosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TorneosRequest.ProtoReflect.Descriptor instead.
func (*TorneosRequest) Descriptor() ([]byte, []int) {
	return file_proto_logic_proto_rawDescGZIP(), []int{1}
}

func (x *TorneosRequest) GetSolicitanteInfo() string {
	if x != nil {
		return x.SolicitanteInfo
	}
	return ""
}

type TorneosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Torneos       []*Torneo              `protobuf:"bytes,1,rep,name=torneos,proto3" json:"torneos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TorneosResponse) Reset() {
	*x = TorneosResponse{}
	mi := &file_proto_logic_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TorneosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TorneosResponse) ProtoMessage() {}

func (x *TorneosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TorneosResponse.ProtoReflect.Descriptor instead.
func (*TorneosResponse) Descriptor() ([]byte, []int) {
	return file_proto_logic_proto_rawDescGZIP(), []int{2}
}

func (x *TorneosResponse) GetTorneos() []*Torneo {
	if x != nil {
		return x.Torneos
	}
	return nil
}

// --- Mensajes para InscribirTorneo ---
type InscripcionRequest struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	TorneoId                 string                 `protobuf:"bytes,1,opt,name=torneo_id,json=torneoId,proto3" json:"torneo_id,omitempty"`
	EntrenadorId             string                 `protobuf:"bytes,2,opt,name=entrenador_id,json=entrenadorId,proto3" json:"entrenador_id,omitempty"`
	EntrenadorNombre         string                 `protobuf:"bytes,3,opt,name=entrenador_nombre,json=entrenadorNombre,proto3" json:"entrenador_nombre,omitempty"`                            // Útil para logs en el servidor
	EntrenadorRegion         string                 `protobuf:"bytes,4,opt,name=entrenador_region,json=entrenadorRegion,proto3" json:"entrenador_region,omitempty"`                            // Podría ser útil para validaciones en el servidor
	EntrenadorSuspensionDias int32                  `protobuf:"varint,5,opt,name=entrenador_suspension_dias,json=entrenadorSuspensionDias,proto3" json:"entrenador_suspension_dias,omitempty"` // Días de suspensión actuales del entrenador
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *InscripcionRequest) Reset() {
	*x = InscripcionRequest{}
	mi := &file_proto_logic_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InscripcionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InscripcionRequest) ProtoMessage() {}

func (x *InscripcionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InscripcionRequest.ProtoReflect.Descriptor instead.
func (*InscripcionRequest) Descriptor() ([]byte, []int) {
	return file_proto_logic_proto_rawDescGZIP(), []int{3}
}

func (x *InscripcionRequest) GetTorneoId() string {
	if x != nil {
		return x.TorneoId
	}
	return ""
}

func (x *InscripcionRequest) GetEntrenadorId() string {
	if x != nil {
		return x.EntrenadorId
	}
	return ""
}

func (x *InscripcionRequest) GetEntrenadorNombre() string {
	if x != nil {
		return x.EntrenadorNombre
	}
	return ""
}

func (x *InscripcionRequest) GetEntrenadorRegion() string {
	if x != nil {
		return x.EntrenadorRegion
	}
	return ""
}

func (x *InscripcionRequest) GetEntrenadorSuspensionDias() int32 {
	if x != nil {
		return x.EntrenadorSuspensionDias
	}
	return 0
}

type InscripcionResponse struct {
	state              protoimpl.MessageState  `protogen:"open.v1"`
	Exito              bool                    `protobuf:"varint,1,opt,name=exito,proto3" json:"exito,omitempty"`                                                                      // true si la inscripción fue exitosa, false si no
	Mensaje            string                  `protobuf:"bytes,2,opt,name=mensaje,proto3" json:"mensaje,omitempty"`                                                                   // Mensaje descriptivo del resultado
	TorneoIdConfirmado string                  `protobuf:"bytes,3,opt,name=torneo_id_confirmado,json=torneoIdConfirmado,proto3" json:"torneo_id_confirmado,omitempty"`                 // El ID del torneo al que se inscribió (si exito=true)
	RazonRechazo       RazonRechazoInscripcion `protobuf:"varint,4,opt,name=razon_rechazo,json=razonRechazo,proto3,enum=proto.RazonRechazoInscripcion" json:"razon_rechazo,omitempty"` // Razón específica si exito = false
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *InscripcionResponse) Reset() {
	*x = InscripcionResponse{}
	mi := &file_proto_logic_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InscripcionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InscripcionResponse) ProtoMessage() {}

func (x *InscripcionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_logic_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InscripcionResponse.ProtoReflect.Descriptor instead.
func (*InscripcionResponse) Descriptor() ([]byte, []int) {
	return file_proto_logic_proto_rawDescGZIP(), []int{4}
}

func (x *InscripcionResponse) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *InscripcionResponse) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

func (x *InscripcionResponse) GetTorneoIdConfirmado() string {
	if x != nil {
		return x.TorneoIdConfirmado
	}
	return ""
}

func (x *InscripcionResponse) GetRazonRechazo() RazonRechazoInscripcion {
	if x != nil {
		return x.RazonRechazo
	}
	return RazonRechazoInscripcion_RAZON_DESCONOCIDA
}

var File_proto_logic_proto protoreflect.FileDescriptor

const file_proto_logic_proto_rawDesc = "" +
	"\n" +
	"\x11proto/logic.proto\x12\x05proto\"0\n" +
	"\x06Torneo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06region\x18\x02 \x01(\tR\x06region\";\n" +
	"\x0eTorneosRequest\x12)\n" +
	"\x10solicitante_info\x18\x01 \x01(\tR\x0fsolicitanteInfo\":\n" +
	"\x0fTorneosResponse\x12'\n" +
	"\atorneos\x18\x01 \x03(\v2\r.proto.TorneoR\atorneos\"\xee\x01\n" +
	"\x12InscripcionRequest\x12\x1b\n" +
	"\ttorneo_id\x18\x01 \x01(\tR\btorneoId\x12#\n" +
	"\rentrenador_id\x18\x02 \x01(\tR\fentrenadorId\x12+\n" +
	"\x11entrenador_nombre\x18\x03 \x01(\tR\x10entrenadorNombre\x12+\n" +
	"\x11entrenador_region\x18\x04 \x01(\tR\x10entrenadorRegion\x12<\n" +
	"\x1aentrenador_suspension_dias\x18\x05 \x01(\x05R\x18entrenadorSuspensionDias\"\xbc\x01\n" +
	"\x13InscripcionResponse\x12\x14\n" +
	"\x05exito\x18\x01 \x01(\bR\x05exito\x12\x18\n" +
	"\amensaje\x18\x02 \x01(\tR\amensaje\x120\n" +
	"\x14torneo_id_confirmado\x18\x03 \x01(\tR\x12torneoIdConfirmado\x12C\n" +
	"\rrazon_rechazo\x18\x04 \x01(\x0e2\x1e.proto.RazonRechazoInscripcionR\frazonRechazo*\x8f\x01\n" +
	"\x17RazonRechazoInscripcion\x12\x15\n" +
	"\x11RAZON_DESCONOCIDA\x10\x00\x12\x1a\n" +
	"\x16RECHAZO_POR_SUSPENSION\x10\x01\x12#\n" +
	"\x1fRECHAZO_YA_INSCRITO_OTRO_TORNEO\x10\x02\x12\x1c\n" +
	"\x18RECHAZO_TORNEO_NO_EXISTE\x10\x032\xaa\x01\n" +
	"\fContactarLCP\x12N\n" +
	"\x1bConsultarTorneosDisponibles\x12\x15.proto.TorneosRequest\x1a\x16.proto.TorneosResponse\"\x00\x12J\n" +
	"\x0fInscribirTorneo\x12\x19.proto.InscripcionRequest\x1a\x1a.proto.InscripcionResponse\"\x00B\x1aZ\x18DISTROTAREA2/proto/protob\x06proto3"

var (
	file_proto_logic_proto_rawDescOnce sync.Once
	file_proto_logic_proto_rawDescData []byte
)

func file_proto_logic_proto_rawDescGZIP() []byte {
	file_proto_logic_proto_rawDescOnce.Do(func() {
		file_proto_logic_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_logic_proto_rawDesc), len(file_proto_logic_proto_rawDesc)))
	})
	return file_proto_logic_proto_rawDescData
}

var file_proto_logic_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_logic_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_logic_proto_goTypes = []any{
	(RazonRechazoInscripcion)(0), // 0: proto.RazonRechazoInscripcion
	(*Torneo)(nil),               // 1: proto.Torneo
	(*TorneosRequest)(nil),       // 2: proto.TorneosRequest
	(*TorneosResponse)(nil),      // 3: proto.TorneosResponse
	(*InscripcionRequest)(nil),   // 4: proto.InscripcionRequest
	(*InscripcionResponse)(nil),  // 5: proto.InscripcionResponse
}
var file_proto_logic_proto_depIdxs = []int32{
	1, // 0: proto.TorneosResponse.torneos:type_name -> proto.Torneo
	0, // 1: proto.InscripcionResponse.razon_rechazo:type_name -> proto.RazonRechazoInscripcion
	2, // 2: proto.ContactarLCP.ConsultarTorneosDisponibles:input_type -> proto.TorneosRequest
	4, // 3: proto.ContactarLCP.InscribirTorneo:input_type -> proto.InscripcionRequest
	3, // 4: proto.ContactarLCP.ConsultarTorneosDisponibles:output_type -> proto.TorneosResponse
	5, // 5: proto.ContactarLCP.InscribirTorneo:output_type -> proto.InscripcionResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_logic_proto_init() }
func file_proto_logic_proto_init() {
	if File_proto_logic_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_logic_proto_rawDesc), len(file_proto_logic_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_logic_proto_goTypes,
		DependencyIndexes: file_proto_logic_proto_depIdxs,
		EnumInfos:         file_proto_logic_proto_enumTypes,
		MessageInfos:      file_proto_logic_proto_msgTypes,
	}.Build()
	File_proto_logic_proto = out.File
	file_proto_logic_proto_goTypes = nil
	file_proto_logic_proto_depIdxs = nil
}
